/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
 
    // Or if using `src` directory:
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "on-tertiary-fixed": "#131b2e",
        "inverse-surface": "#2d3133",
        "tertiary-fixed-dim": "#bec6e0",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#1e3a8a",
        "surface-container": "#eceef0",
        "secondary-fixed": "#6ffbbe",
        "inverse-on-surface": "#eff1f3",
        "outline": "#757682",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-tint": "#4059aa",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#264191",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#90a8ff",
        "tertiary-fixed": "#dae2fd",
        "secondary-container": "#6cf8bb",
        "secondary": "#006c49",
        "primary-fixed-dim": "#b6c4ff",
        "on-error": "#ffffff",
        "tertiary-container": "#384055",
        "inverse-primary": "#b6c4ff",
        "primary-fixed": "#dce1ff",
        "on-tertiary-container": "#a4acc5",
        "on-primary": "#ffffff",
        "on-surface-variant": "#444651",
        "on-surface": "#191c1e",
        "background": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "tertiary": "#222a3e",
        "outline-variant": "#c5c5d3",
        "primary": "#00236f",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#00164e",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-secondary-container": "#00714d",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-high": "#e6e8ea",
        "surface-container-low": "#f2f4f6",
        "surface-container-highest": "#e0e3e5"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        lg: "24px",
        sm: "8px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        md: "16px",
        base: "4px",
        gutter: "24px",
        "2xl": "48px",
        xs: "4px",
        xl: "32px",
        "3xl": "64px"
      },
      fontFamily: {
        "display-lg": ["Inter"],
        "headline-sm": ["Inter"],
        "label-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
